### ISSUE TITLE
2 bugs : duplicated items + shared folders that disappeared from 'sharing area'

### ISSUE THREAD

**Issue by andrii482** [482solutions/woden-server-js#88]
steps:

register `user1` , (register `user2`, `user3`), login, create folders structure, share all folders to `user2`, via `user1` upload file to folder and share this folder to `user3`.
In this point - in `user3` signing/share areas appear duplicated items (may be because there was sharing of folder, but not file)
![image](https://user-images.githubusercontent.com/61418776/166234760-5847f8b6-810a-413e-8898-4864029e261d.png)
![image](https://user-images.githubusercontent.com/61418776/166234913-2988e063-2d8a-4a1f-81a6-f3ee63ebe4f0.png)

Also, all sharing folders for `user2` are dissapeared in it's 'sharing area'
After, new sharing and new voting - any of this ^ two bugs don't appeared.
Also, any error messages in docker logs (backend, chaincode, peer) - not appeared

**Comment by andrii482** [comment]
```
send to fabric  updateVoting 1
2022-05-02T12:04:56.430Z - warn: [TransactionEventHandler]: _strategyFail: strategy fail for transaction "400ca84ee8775b167afe4ee5cbb46f0c52ffbbfbab93c90e02fd380d22ae16d9": TransactionError: Peer 161.35.204.191:7051 has rejected transaction "400ca84ee8775b167afe4ee5cbb46f0c52ffbbfbab93c90e02fd380d22ae16d9" with code "MVCC_READ_CONFLICT"
    at TransactionEventHandler._onEvent (/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:114:23)
    at EventRegistration._onEventFn (/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:88:26)
    at EventRegistration.onEvent (/app/node_modules/fabric-network/node_modules/fabric-client/lib/ChannelEventHub.js:1788:9)
    at Proxy._callTransactionListener (/app/node_modules/fabric-network/node_modules/fabric-client/lib/ChannelEventHub.js:1480:13)
    at Proxy._checkTransactionId (/app/node_modules/fabric-network/node_modules/fabric-client/lib/ChannelEventHub.js:1464:9)
    at Proxy._processTxEvents (/app/node_modules/fabric-network/node_modules/fabric-client/lib/ChannelEventHub.js:1443:11)
    at ClientDuplexStream.<anonymous> (/app/node_modules/fabric-network/node_modules/fabric-client/lib/ChannelEventHub.js:521:11)
    at ClientDuplexStream.emit (events.js:210:5)
    at ClientDuplexStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12) {
  transactionId: '400ca84ee8775b167afe4ee5cbb46f0c52ffbbfbab93c90e02fd380d22ae16d9',
  transactionCode: 'MVCC_READ_CONFLICT',
  name: 'TransactionError'
}
send to fabric  updateVoting 2
send to fabric  updateVoting 1
send to fabric  getFolder 1

```
